### ISSUE TITLE
Ability to extract resources in memory

### ISSUE THREAD

**Issue by minton** [bytejoyhq/resourcer#1]
# Use Case

I want to store SQL scripts as embedded resources in my application. I want to be able to retrieve the SQL script as a string without first saving to disk.

# Proposal

```c#
public static string ExtractResource(this Assembly assembly, string resourceName){ ... }
```

**Comment by minton** [comment]
Hi thanks for the addition but I don't see a new package in nuget?

**Comment by siegol** [comment]
There is sometimes a delay before the package shows up while nuget indexes things.
